HEADER_DIRS := enums scoped
CAGOUL_PUBLIC_HEADERS := \
	$(patsubst $(top_srcdir)cagoul/%,%, \
		$(wildcard $(top_srcdir)cagoul/*.hpp) \
		$(foreach d,$(HEADER_DIRS),$(wildcard $(top_srcdir)cagoul/$(d)/*.hpp)) \
	)
INCLUDE_TESTS := \
	$(addsuffix .include.cpp,$(basename $(CAGOUL_PUBLIC_HEADERS)))
STRAY_INCLUDE_TESTS := \
	$(filter-out $(INCLUDE_TESTS),$(wildcard *.include.cpp))

BIN := cagoul-test
LIBS := -lboost_unit_test_framework
GEN_SOURCES := $(INCLUDE_TESTS)
EXCLUDE_FILES := $(STRAY_INCLUDE_TESTS)

$(INCLUDE_TESTS): %.include.cpp:
	mkdir -p $(dir $@)
	printf '#include <cagoul/%s.hpp>\n' '$*' > $@

test-nonrecursive: $(BIN)
	./$<

clean:
	rm -rf *.include.cpp $(HEADER_DIRS)

