SUBDIRS := cagoul test examples

all-recurse-examples all-recurse-test: all-recurse-cagoul

test-recurse-examples test-recurse-test: test-recurse-cagoul

.PHONY: doc
doc:
	# Redirect because doxygen doesn't flush stdout properly
	doxygen >/dev/null

