#ifndef CAGOUL_DETAIL__BRACES_IF_DOXYGEN_HPP
#define CAGOUL_DETAIL__BRACES_IF_DOXYGEN_HPP

#ifdef DOXYGEN
#define CAGOUL_DETAIL_BRACES_IF_DOXYGEN {}
#else
#define CAGOUL_DETAIL_BRACES_IF_DOXYGEN
#endif

#endif // CAGOUL_DETAIL__BRACES_IF_DOXYGEN_HPP

