#ifndef CAGOUL_ENUMS__TEXIMAGE_DINTERNALFORMAT_HPP
#define CAGOUL_ENUMS__TEXIMAGE_DINTERNALFORMAT_HPP

#include <cagoul/detail/define_scoped_enum.hpp>

namespace cagoul { namespace enums {

#define CAGOUL_ENUMS_TEXIMAGE2DINTERNALFORMAT_VALUES \
  (ALPHA) \
  (ALPHA4) \
  (ALPHA8) \
  (ALPHA12) \
  (ALPHA16) \
  (COMPRESSED_ALPHA) \
  (COMPRESSED_LUMINANCE) \
  (COMPRESSED_LUMINANCE_ALPHA) \
  (COMPRESSED_INTENSITY) \
  (COMPRESSED_RGB) \
  (COMPRESSED_RGBA) \
  (DEPTH_COMPONENT) \
  (DEPTH_COMPONENT16) \
  (DEPTH_COMPONENT24) \
  (DEPTH_COMPONENT32) \
  (LUMINANCE) \
  (LUMINANCE4) \
  (LUMINANCE8) \
  (LUMINANCE12) \
  (LUMINANCE16) \
  (LUMINANCE_ALPHA) \
  (LUMINANCE4_ALPHA4) \
  (LUMINANCE6_ALPHA2) \
  (LUMINANCE8_ALPHA8) \
  (LUMINANCE12_ALPHA4) \
  (LUMINANCE12_ALPHA12) \
  (LUMINANCE16_ALPHA16) \
  (INTENSITY) \
  (INTENSITY4) \
  (INTENSITY8) \
  (INTENSITY12) \
  (INTENSITY16) \
  (R3_G3_B2) \
  (RGB) \
  (RGB4) \
  (RGB5) \
  (RGB8) \
  (RGB10) \
  (RGB12) \
  (RGB16) \
  (RGBA) \
  (RGBA2) \
  (RGBA4) \
  (RGB5_A1) \
  (RGBA8) \
  (RGB10_A2) \
  (RGBA12) \
  (RGBA16) \
  (SLUMINANCE) \
  (SLUMINANCE8) \
  (SLUMINANCE_ALPHA) \
  (SLUMINANCE8_ALPHA8) \
  (SRGB) \
  (SRGB8) \
  (SRGB_ALPHA) \
  (SRGB8_ALPHA8)

/** \brief Scoped enumeration of potential arguments to the internalFormat
 * argument of glTexImage2D / cagoul::TexImage2D. */
CAGOUL_DETAIL_DEFINE_SCOPED_ENUM(
  TexImage2DInternalFormat, CAGOUL_ENUMS_TEXIMAGE2DINTERNALFORMAT_VALUES
)

}}

#endif // CAGOUL_ENUMS__TEXIMAGE_DINTERNALFORMAT_HPP

